api_platform:
    title: Hello API Platform
    version: 1.0.0
    mapping:
        paths: 
            - '%kernel.project_dir%/src/Entity'
    patch_formats:
        json: [ 'application/merge-patch+json' ]
        jsonapi: [ 'application/vnd.api+json' ]
    formats:
        jsonld: [ 'application/json','application/ld+json' ]
        jsonapi: [ 'application/vnd.api+json' ]
        html: [ 'text/html' ]
    
    error_formats:
        jsonld: [ 'application/ld+json' ]
        jsonapi: [ 'application/vnd.api+json' ]
    
    
    enable_swagger_ui: true
    enable_re_doc: true
    
    swagger:
        versions: [3]
        api_keys:
            JWT:
                name: Authorization
                type: header
    collection:
        pagination:
            page_parameter_name: page
            items_per_page_parameter_name: per_page
    
    # Mercure integration, remove if unwanted
    mercure: ~
    # Good cache defaults for REST APIs
    defaults:
        pagination_items_per_page: 30
        pagination_client_items_per_page: true
        pagination_maximum_items_per_page: 100
            
        stateless: true
        normalization_context: 
            skip_null_values: false
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
            
