framework:
    messenger:

        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
             'App\Entity\MediaObject': async

when@test:
   framework:
       messenger:
           transports:
               async: test://
