parameters:
    env(AWS_S3_READ_ENDPOINT): null
    env(AWS_S3_WRITE_ENDPOINT): null

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    
    App\Serializer\SerialisationGroupGenerator:
        decorates: 'api_platform.serializer.context_builder'
        arguments:
            $decorated: '@App\Serializer\SerialisationGroupGenerator.inner'


    ### Services
    App\Service\MediaUploader:
        class: App\Service\MediaUploader
        arguments:
            $s3ReadClient: '@s3.read.client'
            $bucket: '%env(AWS_S3_BUCKET)%'
    
    s3.read.client:
        class: Aws\S3\S3Client
        arguments:
            -   version: '2006-03-01'
                endpoint: '%env(AWS_S3_READ_ENDPOINT)%'
                region: '%env(AWS_REGION)%'
                use_path_style_endpoint: true
    
    s3.write.client:
        class: Aws\S3\S3Client
        arguments:
            -   version: '2006-03-01'
                endpoint: '%env(AWS_S3_WRITE_ENDPOINT)%'
                region: '%env(AWS_REGION)%'
                use_path_style_endpoint: true    
    
    ### Documentation
    App\OpenApi\AuthDecorator:
        decorates: 'api_platform.openapi.factory'


    ### Entity listeners
    App\Doctrine\EntityListener\UserListener:
        tags:
            - { name: doctrine.orm.entity_listener, priority: 10 }



    ### State Processors
    App\State\User\UserProcessor:
        bind:
            $decorated: '@ApiPlatform\Doctrine\Common\State\PersistProcessor'
    
    App\State\Product\ProductProcessor:
        bind:
            $decorated: '@ApiPlatform\Doctrine\Common\State\PersistProcessor'
