parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    
    App\Serializer\SerialisationGroupGenerator:
        decorates: 'api_platform.serializer.context_builder'
        arguments:
            $decorated: '@App\Serializer\SerialisationGroupGenerator.inner'
    

    ### Documentation
    App\OpenApi\AuthDecorator:
        decorates: 'api_platform.openapi.factory'



    ### Entity listeners
    App\Doctrine\EntityListener\UserListener:
        tags:
            - { name: doctrine.orm.entity_listener, priority: 10 }



    ### State Processors
    App\State\User\UserProcessor:
        bind:
            $decorated: '@ApiPlatform\Doctrine\Common\State\PersistProcessor'
