name: CI

on:
  push:
    branches:
      - "*"
  pull_request: ~
  workflow_dispatch: ~

concurrency:
  group: ci-phpunit-${{ github.ref }}-1
  cancel-in-progress: true


jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Pull images
        run: docker-compose pull --ignore-pull-failures || true
        
      - name: Start services
        run: docker-compose up --build -d
        
      - name: Check HTTPS reachability
        run: curl  -vk -o /dev/null https://localhost
        
      - name: Create test database
        run: |
          docker-compose exec -T php bin/console -e test doctrine:database:create
          docker-compose exec -T php bin/console -e test doctrine:migrations:migrate --no-interaction
      - name: PHPUnit
        run: docker-compose exec -T php bin/phpunit
      - name: Doctrine Schema Validator
        run: docker-compose exec -T php bin/console doctrine:schema:validate --skip-sync
